apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise"
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "glusterfs-storage" # ! edit according to infrastructure
    volumeSize: "1Gi"
  uiServiceType: ClusterIP
  username: "demo@redislabs.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: "4000m"
      memory: 4Gi
    requests:
      cpu: "4000m"
      memory: 4Gi
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       docker-registry.default.svc:5000/openshift/redis-enterprise
    versionTag:       6.0.8-28.rhel7-openshift
  redisEnterpriseServicesRiggerImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       docker-registry.default.svc:5000/openshift/k8s-controller
    versionTag:       6.0.8-1
  bootstrapperImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       docker-registry.default.svc:5000/openshift/redis-enterprise-operator
    versionTag:       6.0.8-1    
